<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DELL-PC" name="Test - 1" tests="1" failures="1" timestamp="17 Mar 2020 13:18:00 GMT" time="80.577" errors="0">
  <testcase name="feature" time="77.879" classname="runners.TestRunnerTestNg">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [new test fail] but found [new test]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [new test fail] but found [new test]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: expected [new test fail] but found [new test]
	at stepDefinitions.HomePageSteps.failStep(HomePageSteps.java:32)
	at âœ½.When Execute fail step(End2End_Test.feature:14)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Test - 1 -->
